# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build Raylib-CSharp

on:
  release:
    types: [ "published" ]
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  raylib_version: '5.0'

jobs:
  
  # Build for Win
  build-win:
    runs-on: windows-latest
    strategy:
      matrix:
        name: [win32, x64]
    
    # Run
    steps:
      - uses: actions/checkout@v4
        
      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # Build Raylib
      - name: Build Raylib
        shell: bash
        run: |
          curl -Lso raylib.zip https://github.com/raysan5/raylib/archive/refs/tags/${{ env.raylib_version }}.zip
          unzip -qq raylib.zip
          cmake -S raylib-${{ env.raylib_version }} \
          -A ${{ matrix.name }} \
          -B native \
          -D CMAKE_BUILD_TYPE=Release \
          -D BUILD_SHARED_LIBS=ON \
          -D BUILD_EXAMPLES=OFF \
          -D CUSTOMIZE_BUILD=ON \
          -D SUPPORT_GIF_RECORDING=OFF \
          -D SUPPORT_SCREEN_CAPTURE=OFF
          cmake --build native --config Release

      # Upload Raylib
      - name: Upload Raylib
        uses: actions/upload-artifact@v4
        with:
          name: win-${{ matrix.name }}
          path: native/raylib/Release/raylib.dll
          if-no-files-found: error
    
  # Build for Linux
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: [x64]
    
    # Run
    steps:
      - uses: actions/checkout@v4
        
      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      
      # Setup dependencies
      - name: Setup dependencies
        run: |
          sudo apt-get install -y \
            libasound2-dev \
            libxrandr-dev \
            libx11-dev \
            libxi-dev \
            libgl1-mesa-dev \
            libglu1-mesa-dev \
            libxcursor-dev \
            libxinerama-dev

      # Build Raylib
      - name: Build Raylib
        run: |
          curl -Lso raylib.zip https://github.com/raysan5/raylib/archive/refs/tags/${{ env.raylib_version }}.zip
          unzip -qq raylib.zip
          cmake -S raylib-${{ env.raylib_version }} \
          -B native \
          -D CMAKE_BUILD_TYPE=Release \
          -D BUILD_SHARED_LIBS=ON \
          -D BUILD_EXAMPLES=OFF \
          -D CUSTOMIZE_BUILD=ON \
          -D SUPPORT_GIF_RECORDING=OFF \
          -D SUPPORT_SCREEN_CAPTURE=OFF
          cmake --build native --config Release

      # Upload Raylib
      - name: Upload Raylib
        uses: actions/upload-artifact@v4
        with:
          name: linux-${{ matrix.name }}
          path: native/raylib/libraylib.so
          if-no-files-found: error
          
  # Build for OSX
  build-osx:
    runs-on: macos-latest
    strategy:
      matrix:
        name: [arm64, x86_64]
    
    # Run
    steps:
      - uses: actions/checkout@v4
        
      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # Build Raylib
      - name: Build Raylib
        run: |
          curl -Lso raylib.zip https://github.com/raysan5/raylib/archive/refs/tags/${{ env.raylib_version }}.zip
          unzip -qq raylib.zip
          cmake -S raylib-${{ env.raylib_version }} \
          -B native \
          -D CMAKE_BUILD_TYPE=Release \
          -D CMAKE_OSX_ARCHITECTURES=${{ matrix.name }} \
          -D BUILD_SHARED_LIBS=ON \
          -D BUILD_EXAMPLES=OFF \
          -D CUSTOMIZE_BUILD=ON \
          -D SUPPORT_GIF_RECORDING=OFF \
          -D SUPPORT_SCREEN_CAPTURE=OFF
          cmake --build native --config Release

      # Upload Raylib
      - name: Upload Raylib
        uses: actions/upload-artifact@v4
        with:
          name: osx-${{ matrix.name }}
          path: native/raylib/libraylib.dylib
          if-no-files-found: error
          
  # Publish to NuGet
  publish-nuget:
    runs-on: ubuntu-latest
    needs: [build-win, build-linux, build-osx]
    
    # Run
    steps:
      - uses: actions/checkout@v4
      
      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          
      # Setup dependencies
      - name: Setup dependencies
        run: |
          sudo apt-get install -y \
            libasound2-dev \
            libxrandr-dev \
            libx11-dev \
            libxi-dev \
            libgl1-mesa-dev \
            libglu1-mesa-dev \
            libxcursor-dev \
            libxinerama-dev

      # Restore NuGet packages
      - name: Restore NuGet packages
        run: dotnet restore

      # Build and pack NuGet package
      - name: Build and pack NuGet package
        if: github.event_name == 'release'
        run: dotnet pack -p:PackageVersion=${{ steps.get_version.outputs.VERSION }} --configuration Release --output nuget

      # Publish NuGet package
      - name: Publish NuGet package
        if: github.event_name == 'release'
        run: dotnet nuget push nuget/* -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}